#!/bin/bash

set -ex

this_ip="$1"; shift
this_machine="$1"; shift
consul_args="$@"

etcdcurl="curl -sL http://${this_ip}:4001/v2/keys/consul.io/bootstrap/machines/"

function leave-cluster {
  ${etcdcurl}${this_machine} -XDELETE
  /bin/consul leave || true
  sleep 5
}

trap leave-cluster EXIT

$etcdcurl -XPUT -d dir=true

first_node_value="$(${etcdcurl} | jq '.node.nodes[0].value' | tr -d "\"")"

if [[ "$first_node_value" != "null" ]]; then
  join_arg="--join ${first_node_value}"
fi

${etcdcurl}${this_machine} -XPUT -d value=${this_ip}

/bin/consul agent -server \
            -bootstrap-expect 3 \
            -advertise ${this_ip} \
            -client 0.0.0.0 \
            -ui-dir /ui \
            -data-dir /data/ \
            ${join_arg} $@
